package database;


/**
 * Diese Klasse dient der Initialisierung der Datenbank.
 */
public final class DatabaseStructure {
	
	/** Der Pfad unter dem die Datenbank abgelegt ist. */
	public static final String PATH = "jdbc:hsqldb:datenbank/fourinarow";
	
	/** Der Benutzername der Datenbank. */
	public static final String USER = "sa";
	
	/** Das Passwort für die Datenbank. */
	public static final String PASSWORD = "";
	
	/** SQL-Query um die Tabelle für die Spiele zu erzeugen. */
	public static final String CREATE_TABLE_SPIELE = "CREATE TABLE IF NOT EXISTS spiele ( "
													+ "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
													+ "spielero VARCHAR(256), "
													+ "spielerx VARCHAR(256), "
													+ "sieger VARCHAR(256), "
													+ "datum VARCHAR(256))";
	
	/** SQL-Query um die Tabelle für die Sätze zu erzeugen. */
	public static final String CREATE_TABLE_SAETZE = "CREATE TABLE IF NOT EXISTS saetze ( "
													+ "spiel_id INTEGER, "
													+ "satz_nr INTEGER, "
													+ "punktespielero INTEGER, "
													+ "punktespielerx INTEGER, "
													+ "sieger VARCHAR(256), "
													+ "startspieler VARCHAR(256), "
													+ "PRIMARY KEY(spiel_id, satz_nr))";
	
	/** SQL-Query um die Tabelle für die Züge zu erzeugen. */
	public static final String CREATE_TABLE_ZUEGE = "CREATE TABLE IF NOT EXISTS zuege ( "
													+ "spiel_id INTEGER, "
													+ "satz_nr INTEGER, "
													+ "zug_nr INTEGER, "
													+ "spalte INTEGER, "
													+ "spieler VARCHAR(256), "
													+ "PRIMARY KEY(spiel_id, satz_nr, zug_nr))";
	
}